"""自研实现 (对齐上游 transcript 协议; 纯 stdlib, Python 3.11 惯用写法)。

Public API:
- Builders: :class:`AgentTranscript`, :class:`TranscriptStore`
- Message/model types: see :mod:`qingxiaotuan.ports.transcript.model` and ``ids``
- (De)serialization: :mod:`qingxiaotuan.ports.transcript.serialize` and
  :mod:`qingxiaotuan.ports.transcript.operation` (``snapshot_to_dict`` /
  ``snapshot_from_dict``, ``operation_to_dict`` / ``operation_from_dict``)
"""

from __future__ import annotations

from .exceptions import TranscriptDecodeError
from .ids import (
    AgentId,
    AttachmentId,
    FrameId,
    InteractionId,
    ItemId,
    MarkerId,
    PromptId,
    StepId,
    TaskId,
    TaskRefId,
    TodoId,
    TurnId,
    compare_turn_ids,
    frame_id,
    step_id,
    turn_id,
    turn_ordinal,
)
from .model import (
    AgentRef,
    AgentStatusMeta,
    AgentUsageMeta,
    Frame,
    GoalMeta,
    KNOWN_MARKERS,
    ModesMeta,
    TextFrame,
    ThinkingFrame,
    ToolCallFrame,
    ToolFrameProgress,
    TranscriptAttachment,
    TranscriptFrame,
    TranscriptInteraction,
    TranscriptItem,
    TranscriptMarker,
    TranscriptMeta,
    TranscriptPrompt,
    TranscriptStep,
    TranscriptTask,
    TranscriptTaskRef,
    TranscriptTodo,
    TranscriptTurn,
    TranscriptUsage,
    frame_from_dict,
    frame_to_dict,
    item_from_dict,
    item_id,
    item_to_dict,
)
from .model import StepRetry, StepTiming, StepUsage, TodoItem  # type re-exports
from .operation import (
    AgentTranscriptSnapshot,
    AppendOp,
    AppendTarget,
    AppendTargetFrame,
    AppendTargetTask,
    AttachmentUpsertOp,
    FrameUpsertOp,
    InteractionUpsertOp,
    ItemsRemoveOp,
    MarkerUpsertOp,
    MetaMergeOp,
    Operation,
    PromptUpsertOp,
    ResetOp,
    StepUpsertOp,
    TaskRefUpsertOp,
    TaskUpsertOp,
    TodoUpsertOp,
    TurnUpsertOp,
    operation_from_dict,
    operation_to_dict,
    snapshot_from_dict,
    snapshot_to_dict,
)
from .apply import (
    EMPTY_AGENT_STATE,
    AgentState,
    ApplyResult,
    append_at_offset,
    apply_operation,
)
from .store import (
    AgentDescriptor,
    AgentTranscript,
    Disposable,
    TranscriptStore,
)
from .serialize import (
    deserialize_operation,
    deserialize_snapshot,
    dump_event,
    dump_operation,
    dump_ops_batch,
    dump_snapshot,
    is_plain_agent_id,
    load_event,
    load_operation,
    load_ops_batch,
    load_snapshot,
    serialize_operation,
    serialize_snapshot,
)
from .events import (
    TranscriptEvent,
    TranscriptEventType,
    TranscriptOpsEvent,
    TranscriptResetEvent,
    TRANSCRIPT_EVENT_TYPES,
    event_from_dict,
    event_to_dict,
)
from .granularity import (
    GRADE_RANK,
    TranscriptGrade,
    TranscriptGradeSpec,
    detach_grades,
    filter_ops_for_grade,
    grade_for,
    is_append_only,
    needs_reset_on_transition,
    redact_snapshot_for_grade,
)
from .paginate import paginate_turns
from .view import ViewRegistry
from .media_ref import (
    DaemonFileRef,
    MediaPathTagMatch,
    daemon_file_ref_from_pairing_part,
    match_media_path_tag_text,
    parse_daemon_file_ref,
    parse_daemon_file_ref_file_id,
)
from .history import fold_wire_record_facts, group_messages_into_snapshot

__all__ = [
    "TranscriptDecodeError",
    # ids
    "TurnId",
    "StepId",
    "FrameId",
    "MarkerId",
    "TaskRefId",
    "TaskId",
    "AgentId",
    "InteractionId",
    "AttachmentId",
    "TodoId",
    "PromptId",
    "ItemId",
    "turn_id",
    "step_id",
    "frame_id",
    "compare_turn_ids",
    "turn_ordinal",
    # model
    "TranscriptUsage",
    "StepUsage",
    "StepTiming",
    "StepRetry",
    "TranscriptStep",
    "TranscriptTurn",
    "TextFrame",
    "ThinkingFrame",
    "ToolFrameProgress",
    "AgentRef",
    "ToolCallFrame",
    "NoticeFrame",
    "Frame",
    "TranscriptFrame",
    "TranscriptAttachment",
    "TranscriptInteraction",
    "TodoItem",
    "TranscriptTodo",
    "TranscriptPrompt",
    "TranscriptTask",
    "TranscriptMarker",
    "TranscriptTaskRef",
    "TranscriptItem",
    "item_id",
    "item_to_dict",
    "item_from_dict",
    "frame_to_dict",
    "frame_from_dict",
    "KNOWN_MARKERS",
    "GoalMeta",
    "ModesMeta",
    "AgentUsageMeta",
    "AgentStatusMeta",
    "TranscriptMeta",
    # operations + state
    "AgentState",
    "EMPTY_AGENT_STATE",
    "ApplyResult",
    "apply_operation",
    "append_at_offset",
    "AgentTranscriptSnapshot",
    "ResetOp",
    "TurnUpsertOp",
    "StepUpsertOp",
    "FrameUpsertOp",
    "AppendOp",
    "AppendTarget",
    "AppendTargetFrame",
    "AppendTargetTask",
    "MarkerUpsertOp",
    "TaskRefUpsertOp",
    "TaskUpsertOp",
    "InteractionUpsertOp",
    "AttachmentUpsertOp",
    "TodoUpsertOp",
    "PromptUpsertOp",
    "MetaMergeOp",
    "ItemsRemoveOp",
    "Operation",
    "operation_to_dict",
    "operation_from_dict",
    "snapshot_to_dict",
    "snapshot_from_dict",
    # store
    "AgentTranscript",
    "TranscriptStore",
    "AgentDescriptor",
    "Disposable",
    # serialization
    "dump_snapshot",
    "load_snapshot",
    "serialize_snapshot",
    "deserialize_snapshot",
    "dump_operation",
    "load_operation",
    "serialize_operation",
    "deserialize_operation",
    "dump_ops_batch",
    "load_ops_batch",
    "is_plain_agent_id",
    # events
    "TranscriptResetEvent",
    "TranscriptOpsEvent",
    "TranscriptEvent",
    "TranscriptEventType",
    "TRANSCRIPT_EVENT_TYPES",
    "event_to_dict",
    "event_from_dict",
    "dump_event",
    "load_event",
    # granularity
    "TranscriptGrade",
    "TranscriptGradeSpec",
    "GRADE_RANK",
    "grade_for",
    "needs_reset_on_transition",
    "detach_grades",
    "filter_ops_for_grade",
    "is_append_only",
    "redact_snapshot_for_grade",
    # misc helpers
    "paginate_turns",
    "ViewRegistry",
    "DaemonFileRef",
    "MediaPathTagMatch",
    "match_media_path_tag_text",
    "parse_daemon_file_ref",
    "parse_daemon_file_ref_file_id",
    "daemon_file_ref_from_pairing_part",
    "group_messages_into_snapshot",
    "fold_wire_record_facts",
]
