"""可复现构建锁 (Reproducible Build Lock)。

目标
----
在不依赖网络的前提下, 为当前环境生成一个**确定性的依赖锁文件**:

- ``generate_lock``: 调用 ``pip freeze --all`` 拿到精确版本钉死 (``name==version``),
  并在文件头写入 ``# lock-hash: sha256:...`` (对所有钉死项排序后的哈希),
  后续 ``verify_lock`` 可检测依赖漂移或被篡改。
- ``verify_lock``: 重新 ``pip freeze`` 并与锁文件比对, 返回是否有漂移。

说明: 真正的"可复现构建"还需上游发行包哈希 (``pip hash``) 与离线镜像源;
本模块提供**可验证的版本钉死与漂移检测**这一核心基线, 是迈向完整可复现构建的第一步。
不联网、不下载, 因此可在 CI 中稳定跑。
"""
from __future__ import annotations

import hashlib
import os
import sys
import tempfile
from typing import List, Tuple

_HEADER = "# qingxiaotuan reproducible lock (generated by qingxiaotuan.harden.repro_build)"
_HASH_PREFIX = "# lock-hash: "

# pip freeze 在离线/坏源环境下可能挂起; 工业级必须钉死超时, 失败快速报错而非无限等待。
_PIP_TIMEOUT = 60.0


def _pip_freeze() -> List[str]:
    """运行 ``pip freeze --all`` 返回原始行 (按依赖隔离, 可被测试 monkeypatch)。"""
    from ..core.proc import run_with_tree_kill
    proc = run_with_tree_kill(
        [sys.executable, "-m", "pip", "freeze", "--all"],
        capture_output=True, text=True, timeout=_PIP_TIMEOUT,
    )
    if proc.returncode != 0:
        raise RuntimeError(f"pip freeze 失败: {proc.stderr.strip()}")
    return (proc.stdout or "").splitlines()


def _normalize(lines: List[str]) -> List[str]:
    """过滤掉空行/注释, 去掉环境相关行 (如 -e 可编辑安装 / 文件路径)。"""
    out = []
    for ln in lines:
        ln = ln.strip()
        if not ln or ln.startswith("#"):
            continue
        if ln.startswith("-e ") or ln.startswith("-r ") or ln.startswith("://"):
            continue
        out.append(ln)
    return sorted(out)


def compute_lock_hash(normalized: List[str]) -> str:
    payload = "\n".join(normalized).encode("utf-8")
    return "sha256:" + hashlib.sha256(payload).hexdigest()


def _atomic_write(path: str, content: str) -> None:
    """临时文件 + os.replace 原子替换, 崩溃不留下半截锁文件。"""
    directory = os.path.dirname(os.path.abspath(path))
    os.makedirs(directory, exist_ok=True)
    fd, tmp = tempfile.mkstemp(prefix=".qxt-lock.", suffix=".tmp", dir=directory)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(content)
            f.flush()
            os.fsync(f.fileno())
        os.replace(tmp, path)
    except Exception:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise


def generate_lock(out_path: str = "requirements.lock") -> str:
    """生成 requirements.lock (钉死版本 + lock-hash), 返回路径。"""
    lines = _pip_freeze()
    normalized = _normalize(lines)
    h = compute_lock_hash(normalized)
    content = (
        _HEADER + "\n"
        f"{_HASH_PREFIX}{h}\n"
        "# 钉死版本 (由 pip freeze --all 生成)\n"
        + "\n".join(normalized)
        + "\n"
    )
    _atomic_write(out_path, content)
    return out_path


def _read_lock_hash(path: str) -> str:
    with open(path, "r", encoding="utf-8") as f:
        for ln in f:
            if ln.startswith(_HASH_PREFIX):
                return ln[len(_HASH_PREFIX):].strip()
    return ""


def verify_lock(path: str = "requirements.lock") -> Tuple[bool, List[str]]:
    """校验当前环境是否与锁文件一致。

    返回 (ok, diff_lines): ok=False 时 diff_lines 描述漂移。
    """
    if not os.path.exists(path):
        return False, [f"锁文件不存在: {path}"]
    current = _normalize(_pip_freeze())
    current_h = compute_lock_hash(current)
    stored_h = _read_lock_hash(path)
    if current_h != stored_h:
        # 计算差异细节
        try:
            with open(path, "r", encoding="utf-8") as f:
                locked = _normalize(f.read().splitlines())
        except Exception:  # pragma: no cover
            locked = []
        cur_set = set(current)
        lock_set = set(locked)
        added = sorted(cur_set - lock_set)
        removed = sorted(lock_set - cur_set)
        diff = []
        if added:
            diff.append("环境多出的依赖: " + ", ".join(added))
        if removed:
            diff.append("锁文件有但环境缺失: " + ", ".join(removed))
        if not diff:
            diff.append(f"lock-hash 不一致 (current={current_h} stored={stored_h})")
        return False, diff
    return True, []
