"""Artifacts 工具 (对标 Claude Code Artifacts)。

Claude Code Artifacts:
- 把会话输出发布为私有交互式 Web 页面
- 实时更新 (随 Claude 调查进展而变化)
- 适用于: 事件时间线、调查报告、交互式数据展示

青小团实现:
- artifact 工具: 把 markdown 内容渲染为独立 HTML 文件
- 支持 mermaid 图表、代码高亮、交互式展开/折叠
- 自动打开浏览器预览 (可选)
"""

from __future__ import annotations

import html
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Optional

from ..core.kernel import Kernel, Plugin
from ..tools.base import Tool, ToolContext, string_prop

# HTML 模板 (独立文件, 无外部依赖)
_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<style>
  :root {{ --bg: #1a1b26; --fg: #c0caf5; --accent: #4FA8FF; --dim: #565f89;
           --border: #292e42; --code-bg: #1f2335; --link: #7aa2f7; }}
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{ background: var(--bg); color: var(--fg); font-family: 'SF Mono', 'Fira Code', 'Consolas', monospace;
         font-size: 14px; line-height: 1.6; padding: 2rem; max-width: 900px; margin: 0 auto; }}
  h1 {{ color: var(--accent); border-bottom: 1px solid var(--border); padding-bottom: 0.5rem; margin-bottom: 1rem; }}
  h2 {{ color: var(--accent); margin-top: 1.5rem; margin-bottom: 0.5rem; }}
  h3 {{ color: #bb9af7; margin-top: 1rem; }}
  a {{ color: var(--link); text-decoration: none; }}
  a:hover {{ text-decoration: underline; }}
  pre {{ background: var(--code-bg); border: 1px solid var(--border); border-radius: 6px;
        padding: 1rem; overflow-x: auto; margin: 0.8rem 0; }}
  code {{ font-family: 'SF Mono', 'Fira Code', monospace; }}
  p code {{ background: var(--code-bg); padding: 0.1em 0.4em; border-radius: 3px; font-size: 0.9em; }}
  table {{ border-collapse: collapse; width: 100%; margin: 0.8rem 0; }}
  th, td {{ border: 1px solid var(--border); padding: 0.5rem 0.8rem; text-align: left; }}
  th {{ background: var(--code-bg); color: var(--accent); }}
  blockquote {{ border-left: 3px solid var(--accent); padding-left: 1rem; color: var(--dim); margin: 0.5rem 0; }}
  details {{ margin: 0.5rem 0; padding: 0.5rem; background: var(--code-bg); border-radius: 6px; }}
  summary {{ cursor: pointer; color: var(--accent); font-weight: bold; }}
  .meta {{ color: var(--dim); font-size: 0.85em; margin-bottom: 1rem; }}
  .toc {{ background: var(--code-bg); padding: 1rem; border-radius: 6px; margin-bottom: 1.5rem; }}
  .toc ul {{ list-style: none; padding-left: 1rem; }}
  .toc li {{ margin: 0.2rem 0; }}
  .badge {{ display: inline-block; background: var(--accent); color: var(--bg); padding: 0.1em 0.5em;
           border-radius: 3px; font-size: 0.8em; font-weight: bold; margin-left: 0.5rem; }}
  hr {{ border: none; border-top: 1px solid var(--border); margin: 1.5rem 0; }}
</style>
</head>
<body>
{body}
<div class="meta" style="margin-top:2rem;border-top:1px solid var(--border);padding-top:0.5rem;">
  Generated by 青小团 (Tuan-CLI) Artifact System &middot; {timestamp}
</div>
</body>
</html>"""


def _open_browser(path: Path) -> bool:
    """在默认浏览器中打开文件。"""
    try:
        if sys.platform == "win32":
            os.startfile(str(path))
        elif sys.platform == "darwin":
            subprocess.Popen(["open", str(path)], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        else:
            subprocess.Popen(["xdg-open", str(path)], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        return True
    except Exception:  # noqa: BLE001
        return False


def _create_artifact(
    ctx: ToolContext,
    title: str,
    content: str,
    open_browser: bool = True,
) -> str:
    """把 markdown 内容渲染为 HTML artifact 文件并保存。

    Args:
        title: artifact 标题
        content: markdown 格式的内容
        open_browser: 是否自动在浏览器中打开
    """
    import time
    import datetime

    workspace = Path(ctx.workspace)
    artifacts_dir = workspace / ".qxt" / "artifacts"
    artifacts_dir.mkdir(parents=True, exist_ok=True)

    # 生成文件名
    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_title = re.sub(r"[^\w\-]", "_", title)[:50]
    filename = f"{safe_title}_{timestamp}.html"
    filepath = artifacts_dir / filename

    # markdown → HTML (简单的内联转换, 不依赖外部库)
    body = _markdown_to_html(content, title)

    # 填充模板
    html_content = _HTML_TEMPLATE.format(
        title=html.escape(title),
        body=body,
        timestamp=datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
    )

    from ..core.atomicio import atomic_write_text
    atomic_write_text(filepath, html_content)

    result = f"Artifact 已创建: {filepath.relative_to(workspace)}"
    if open_browser:
        if _open_browser(filepath):
            result += " (已在浏览器中打开)"
        else:
            result += f" (请手动打开: {filepath})"

    # 保留最近 20 个 artifact
    _cleanup_old_artifacts(artifacts_dir, keep=20)

    return result


def _markdown_to_html(md: str, title: str = "") -> str:
    """轻量级 markdown → HTML 转换 (不依赖外部库)。"""
    lines = md.split("\n")
    html_parts = []
    in_code_block = False
    in_list = False
    in_table = False

    if title:
        html_parts.append(f"<h1>{html.escape(title)}</h1>")

    for line in lines:
        stripped = line.strip()

        # 代码块
        if stripped.startswith("```"):
            if in_code_block:
                html_parts.append("</code></pre>")
                in_code_block = False
            else:
                lang = stripped[3:].strip()
                html_parts.append(f'<pre><code class="language-{html.escape(lang)}">')
                in_code_block = True
            continue
        if in_code_block:
            html_parts.append(html.escape(line))
            continue

        # 空行
        if not stripped:
            if in_list:
                html_parts.append("</ul>")
                in_list = False
            if in_table:
                html_parts.append("</tbody></table>")
                in_table = False
            continue

        # 标题
        if stripped.startswith("#"):
            level = len(stripped) - len(stripped.lstrip("#"))
            text = stripped[level:].strip()
            html_parts.append(f"<h{min(level, 3)}>{html.escape(text)}</h{min(level, 3)}>")
            continue

        # 表格行
        if "|" in stripped and stripped.startswith("|"):
            cells = [c.strip() for c in stripped.split("|")[1:-1]]
            if all(set(c) <= set("- :") for c in cells):
                continue  # 跳过分隔行
            if not in_table:
                html_parts.append("<table><thead><tr>")
                for c in cells:
                    html_parts.append(f"<th>{html.escape(c)}</th>")
                html_parts.append("</tr></thead><tbody>")
                in_table = True
            else:
                html_parts.append("<tr>")
                for c in cells:
                    html_parts.append(f"<td>{html.escape(c)}</td>")
                html_parts.append("</tr>")
            continue

        # 列表
        if stripped.startswith("- ") or stripped.startswith("* "):
            if not in_list:
                html_parts.append("<ul>")
                in_list = True
            html_parts.append(f"<li>{html.escape(stripped[2:])}</li>")
            continue

        # 引用
        if stripped.startswith("> "):
            html_parts.append(f"<blockquote>{html.escape(stripped[2:])}</blockquote>")
            continue

        # 分割线
        if stripped in ("---", "***", "___"):
            html_parts.append("<hr>")
            continue

        # 粗体
        text = html.escape(stripped)
        text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
        text = re.sub(r"\*(.+?)\*", r"<em>\1</em>", text)
        text = re.sub(r"`(.+?)`", r"<code>\1</code>", text)
        html_parts.append(f"<p>{text}</p>")

    # 关闭未关闭的标签
    if in_list:
        html_parts.append("</ul>")
    if in_table:
        html_parts.append("</tbody></table>")
    if in_code_block:
        html_parts.append("</code></pre>")

    return "\n".join(html_parts)


def _cleanup_old_artifacts(artifacts_dir: Path, keep: int = 20) -> int:
    """保留最近 N 个 artifact, 清理旧的。"""
    files = sorted(artifacts_dir.glob("*.html"), key=lambda f: f.stat().st_mtime, reverse=True)
    removed = 0
    for f in files[keep:]:
        try:
            f.unlink()
            removed += 1
        except OSError:
            pass
    return removed


class ArtifactPlugin(Plugin):
    name = "tools.artifact"
    provides = []
    requires = ["tool_registry"]

    def activate(self, kernel: Kernel) -> None:
        config = kernel.get("config")
        if config and not config.get("tools.artifact.enabled", True):
            return

        registry = kernel.require("tool_registry")
        registry.register(Tool(
            name="create_artifact",
            description=(
                "把 markdown 内容渲染为独立 HTML artifact 页面并保存到 .qxt/artifacts/。"
                "适用于: 调查报告、事件时间线、代码审查结果、数据分析展示。"
            ),
            parameters={
                "type": "object",
                "properties": {
                    "title": string_prop("Artifact 标题"),
                    "content": string_prop("Markdown 格式的内容"),
                    "open_browser": {
                        "type": "boolean",
                        "description": "是否自动在浏览器中打开 (默认 true)",
                    },
                },
                "required": ["title", "content"],
            },
            handler=_create_artifact,
            group="tools",
        ))
